INSERT INTO USERS (username, point, CREATE_DATE, MODIFIED_DATE)
VALUES ('A', 1000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('B', 2000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('C', 3000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('D', 4000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('E', 5000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

--
INSERT INTO PRODUCT (PRODUCT_NUMBER, name, price, stock, sales ,CREATE_DATE, MODIFIED_DATE)
VALUES (1, 'ㄱ', 1000, 10, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (2, 'ㄴ', 2000, 10, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (3, 'ㄷ', 3000, 10, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (4, 'ㄹ', 4000, 10, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (5, 'ㅁ', 5000, 10, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);